version: "3"
services:
  web:
    image: windy/nodejs
    build: server
    container_name: hearthintellect-web
    hostname: hearthintellect-web
    depends_on:
      - "mongo"
    ports:
    - "4000:3000"
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "build"]
  mongo:
    image: windy/mongo
    build: mongo
    container_name: hearthintellect-mongo
    hostname: hearthintellect-mongo
    ports:
    - "27017:27017"
  nginx:
    image: windy/nginx
    build: web
    container_name: hearthintellect-nginx
    hostname: hearthintellect-nginx
    ports:
    - "80:80"
