version: "3"
services:
  web:
    image: windy/nodejs
    build: server
    container_name: hearthintellect-web
    hostname: hearthintellect-web
    ports:
    - "4000:3000"
  mongo:
    image: windy/mongo
    build: mongo
    container_name: hearthintellect-mongo
    hostname: hearthintellect-mongo
    ports:
    - "27017:27017"
  nginx:
    image: windy/nginx
    build: web
    container_name: hearthintellect-nginx
    hostname: hearthintellect-nginx
    ports:
    - "80:80"
